apiVersion: v1
kind: Secret
metadata:
  name: argocd-infra-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: infra
  project: default
  url: <Git URL вашего репозитория> # Например: git@github.com:ilyalushkevich/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBD/q4kbTbIX/P1W/iTAORMbCq15Ysfof7uWKz+NxbotytR8eVgWC97RXxD5qvc5Ku3reF7bfaQaQn5kg4H/Y9/g=
    -----END OPENSSH PRIVATE KEY-----
