apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-backend-git-writeback-creds
  namespace: argocd
stringData:
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
    1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQQ/6uJG02yF/z9Vv4kwDkTGwqteWLH6
    H+7lis/jcW6LcrUfHlYFgve0V8Q+ar3OSrt63he232kGkJ+ZIOB/2Pf4AAAAoLzcdZC83H
    WQAAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBD/q4kbTbIX/P1W/
    iTAORMbCq15Ysfof7uWKz+NxbotytR8eVgWC97RXxD5qvc5Ku3reF7bfaQaQn5kg4H/Y9/
    gAAAAhAOkS9bNWUBBcbLMkRkdNX4mcGmWPruouWwWNNR6g/cEMAAAAAAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----
