apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LTEuZG9ja2VyLmlvIjp7InVzZXJuYW1lIjoiYm92aW54eDEiLCJwYXNzd29yZCI6ImRja3JfcGF0X0hBVlE2Vm5lZmpaU1hkd1Y5cldXS1NNVnZ1OCIsImF1dGgiOiJZbTkyYVc1NGVERTZaR05yY2w5d1lYUmZTRUZXVVRaV2JtVm1hbHBUV0dSM1ZqbHlWMWRMVTAxV2RuVTQifX19
kind: Secret
metadata:
  name: argocd-image-updater-backend
  namespace: argocd
type: kubernetes.io/dockerconfigjson
